fedsgd:
  invertingconfig:
    attack_lr: 0.03
    at_iterations: 1000
    data_extension: GiaTabularExtension

fedavg:
  invertingconfig:
    attack_lr: 0.03
    at_iterations: 1000
    data_extension: GiaTabularExtension
