base: configs/base.yaml
dataset: configs/dataset/dataset.yaml
model: configs/model/model.yaml
gia: configs/gia/gia.yaml
results: leakpro_output/tabular_gia_sweeps

fl_config_by_protocol:
  fedsgd: configs/fl/fedsgd.yaml
  fedavg: configs/fl/fedavg.yaml

grid:
  base.protocol: [fedsgd]
  model.name: [mlp1, mlp2]
  model.d_hidden: [64, 128]
  fl.full_dataset_passes: [1]
  fl.client_participation: [0.2]
  gia.fedsgd.invertingconfig.at_iterations: [10]
