# base
base:
  protocol: [fedsgd, fedavg]

# dataset
dataset:
  dataset_path_and_meta_path: [[data/binary/adult/adult.csv, data/binary/adult/adult.yaml]]
  batch_size: [1, 4, 16, 64, 256]

# model
model:
  use_preset: true # NOTE: if set true, other model params will be ignored and it will default to presets in default model.yaml. Uncomment to disable to sweep all params.
  name: [small, medium, large]
  d_hidden: [64, 128, 256]
  num_layers: [1, 2, 3]
  norm: [none, batchnorm, layernorm]
  dropout: [0.0, 0.15, 0.3]
  activation: [relu, gelu, silu]

# fl
fl:
  fedsgd:
    full_dataset_passes: [1]
    client_participation: [1.0, 0.5]
  fedavg:
    full_dataset_passes: [1]
    local_steps: [1, 10, 100]
    local_epochs: [1, 10, 100]
    client_participation: [1.0, 0.5]

# gia empty for now frozen configs
gia: {}
